version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: google-closure-compiler
    versions:
    - 20210106.0.0
    - 20210202.0.0
    - 20210302.0.0
  - dependency-name: purescript
    versions:
    - 0.13.8
    - 0.14.0
